### ISSUE TITLE
Microsoft/Bing Satellite Image License 

### ISSUE THREAD

**Issue by jremillard** [jremillard/images-to-osm#2]
Microsoft has contacted me. They are not sure if they are allowed to grant permission for this project to use the bing satellite images. The Microsoft legal team is reviewing it. I may need to use a different source for the images, or change the code to not cache the tiles.

**Comment by pnoll1** [comment]
The  [bing wiki page](https://wiki.openstreetmap.org/wiki/Bing_Maps) has a license that describes what you're allowed to use the imagery for, although there may be a more recent one.  Also [scan aerial](https://github.com/jonasstein/scanaerial) does similar processing to you to map waterways using the python imaging library instead of a neural net.
### Other possible sources
The other possible sources I'm aware of are DigitalGlobe, Esri and Mapbox which license the images to be used for tracing elements and uploading them to openstreetmap.  Their imagery is typically not nearly as detailed, speaking from a US perspective.

**Comment by jremillard** [comment]
Mapbox has agreed to allow the mapbox satellite images to be used with this project. I will be adding support for this next and restarting the project.

**Comment by drewbo** [comment]
@jremillard if you are restarting using Mapbox satellite, let me know if https://github.com/developmentseed/label-maker could be of some help. Happy to discuss it if you have any questions

**Comment by jremillard** [comment]
I am restarting with Mapbox. I just looked at label-maker. I didn't know about it previously, thank you for the pointer. It is pretty interesting. I see two problems with it. First, is that doesn't handle features spilling over tile boundaries. My current code handles this correctly for Bing. Secondly, I don't see a export method for the instance segmentation that  Mask R-CNN needs.

**Comment by drewbo** [comment]
@jremillard thanks for the feedback. The tile boundary problem has [an open ticket](https://github.com/developmentseed/label-maker/issues/31) but we haven't settled on how to resolve yet. Could you link to your approach? For the second issue, I don't think we'll add direct Mask R-CNN support but we have been working up some auxiliary scripts to support [other output formats](https://github.com/developmentseed/label-maker/blob/master/examples/utils/tf_records_generation.py). We would definitely be interested in adding support for Mask R-CNN in that fashion

**Comment by jharpster** [comment]
@jremillard The legal team at Microsoft has reviewed this particular scenario and determined that it is consistent with the current terms of the imagery as it relates to contributing to OSM. You're in good hands collaborating with @drewbo and Mapbox but feel free to use the Bing imagery if it is useful in the areas you're working in.

**Comment by jremillard** [comment]
@jharpster Fantastic!
